# Generated by Django 5.0.1 on 2025-08-07 14:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('numCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('nomCategorie', models.CharField(max_length=50)),
                ('imageCategorie', models.ImageField(blank=True, null=True, upload_to='images/categories/')),
                ('descCategorie', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'db_table': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Classement',
            fields=[
                ('numClassement', models.AutoField(primary_key=True, serialize=False)),
                ('nomClassement', models.CharField(max_length=20)),
                ('quantiteMin', models.FloatField()),
                ('quantiteMax', models.FloatField(blank=True, null=True)),
                ('descClassement', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'db_table': 'classement',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('numClient', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=20)),
                ('contact', models.CharField(blank=True, max_length=17, null=True)),
                ('adresse', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('numCommande', models.AutoField(primary_key=True, serialize=False)),
                ('dateCommande', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=30, null=True)),
                ('numClient', models.ForeignKey(db_column='numClient', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='flutter.client')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'db_table': 'commande',
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('numProduit', models.AutoField(primary_key=True, serialize=False)),
                ('libelleProduit', models.CharField(max_length=20)),
                ('quantite', models.FloatField(default=0)),
                ('prixUnitaire', models.FloatField(blank=True, null=True)),
                ('uniteMesure', models.CharField(blank=True, null=True, verbose_name=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('qrCode', models.ImageField(blank=True, null=True, upload_to='images/produits/qrcode/')),
                ('numCategorie', models.ForeignKey(blank=True, db_column='numCategorie', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='flutter.categorie')),
                ('numClassement', models.ForeignKey(blank=True, db_column='numClassement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produits', to='flutter.classement')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'db_table': 'produit',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('numImage', models.AutoField(primary_key=True, serialize=False)),
                ('nomImage', models.ImageField(blank=True, null=True, upload_to='images/produits/images/')),
                ('numProduit', models.ForeignKey(db_column='numProduit', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='flutter.produit')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Comprendre',
            fields=[
                ('numComprendre', models.AutoField(primary_key=True, serialize=False)),
                ('quantiteCommande', models.FloatField(default=0)),
                ('numCommande', models.ForeignKey(db_column='numCommande', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comprendres', to='flutter.commande')),
                ('numProduit', models.ForeignKey(db_column='numProduit', on_delete=django.db.models.deletion.CASCADE, related_name='comprendres', to='flutter.produit')),
            ],
            options={
                'verbose_name': 'Comprendre',
                'verbose_name_plural': 'Comprendres',
                'db_table': 'comprendre',
            },
        ),
    ]
